project_id = "dbiakjwnlokcwddybhsl"

[auth]
site_url = "https://upick.lovable.app"

[auth.email]
sender_name = "You Pick"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-pack-checkout]
verify_jwt = false

[functions.search-places]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.post-spin-to-feed]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.get-cities-in-region]
verify_jwt = false
