project_id = "dbiakjwnlokcwddybhsl"

[auth]
site_url = "https://upick.lovable.app"

[auth.email]
sender_name = "You Pick"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-pack-checkout]
verify_jwt = false
